server:
  port: 80

spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.131:8848

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=Path=/*/msm/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=Path=/*/ucenter/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
