#server:
#  port: 8201  # 服务端口
#
#spring:
#  application:
#    name: service-hosp   # 服务名
#  profiles: # 环境设置：dev、test、prod
#    active: dev
#  datasource: # mysql数据库连接
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.174.131:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  jackson: #返回json的全局时间格式
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
#mybatis-plus: #mybatisplus日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl